import {
    AbstractExecuteCommandHandler,
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, ExecuteCommandAcceptor, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { parseAndGenerate } from '../cli';
import { StGeneratedModule, StGeneratedSharedModule } from './generated/module';
import { StValidator, registerValidationChecks } from './st-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type StAddedServices = {
    validation: {
        StValidator: StValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type StServices = LangiumServices & StAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const StModule: Module<StServices, PartialLangiumServices & StAddedServices> = {
    validation: {
        StValidator: () => new StValidator()
    }
};

class StContentHandler extends AbstractExecuteCommandHandler {
    registerCommands(acceptor: ExecuteCommandAcceptor): void {
        acceptor('generateStJson', args => {
            console.info('generateStJson called');
            console.info(args);
            // invoke generator on this data, and return response
            return parseAndGenerate(args[0]);
        });
    }
}

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createStServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    St: StServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        StGeneratedSharedModule
    );
    const St = inject(
        createDefaultModule({ shared }),
        StGeneratedModule,
        StModule
    );
    shared.ServiceRegistry.register(St);

    shared.lsp.ExecuteCommandHandler = new StContentHandler();
    registerValidationChecks(St);
    return { shared, St };
}
